In [1]:
import numpy as np

#### Creating and accessing numpy array

In [20]:
l = [1, 2, 3, 4, 5]
print((l), type(l))
# 1D Array
# a = np.array([1, 2, 3, 4, 5])
# Creation dtype is optional
a = np.array(l, dtype='float64')
print((a, type(a), a.dtype))

# using arange
a2 = np.arange(9)
a3 = np.arange(1,10)
a4 = np.arange(1,10,3, dtype='float')
print(a2)
print(a3)
print(a4)

# Getting elements and slicing
print(a)
print(a[-2])
print(a[3])
print(a[1:-1])
print(a[1:5])


[1, 2, 3, 4, 5] <class 'list'>
(array([1., 2., 3., 4., 5.]), <class 'numpy.ndarray'>, dtype('float64'))
[0 1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[1. 4. 7.]
[1. 2. 3. 4. 5.]
4.0
4.0
[2. 3. 4.]
[2. 3. 4. 5.]


In [30]:
# Multi Dimentional Array Creation and selection
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[1,1])
print(a[1,2])

b = np.arange(11,20)
print(b)
b = b.reshape((3,3))
print(b)
c = np.arange(11,23).reshape((4,3))
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
6
[11 12 13 14 15 16 17 18 19]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [ ]:
# Slicing
print(c)
print(c[1:3,1:])
print(c[2,1])

# Explore slicing with -

In [ ]:
# array of zeros or ones and random integer with certain dimention
# Zeros
z = np.zeros((5,4))
print(z)
# Ones
o = np.ones((3,4))
print(o)
# Random
r = np.random.randint(1,100, (6,6))
print(r)


In [ ]:
# Flattening multi d array to 1 d array using flatten
print(r)
print(r.flatten())


In [49]:
# Transpose row to col and vice versa using transpose
na = np.arange(10,20).reshape(5,2)
print(na)
na_transposed = na.transpose()
print(na_transposed)


[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[10 12 14 16 18]
 [11 13 15 17 19]]


#### Basic Functionalities

In [53]:
# type(), dtype, ndim, shape, size, 
print(na)
print(type(na))
print(na.dtype)
print(na.ndim)
print(na.shape)
print(na.size)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
<class 'numpy.ndarray'>
int32
2
(5, 2)
10


#### Airthmetic operations

In [ ]:
# Calculation with given number
print(na)
print(na+2)
print(na**2)
print(na%2)
print(na//2)
print(na/2)


In [ ]:
# Calculation with two different arrays
a1 = na
a2 = na+2
print(a1)
print(a2)
print(a2-a1)
print(a2/a1)
print(a2+a1)
print(a2*a1)
print(a2**a1)

#### Type Casting

In [67]:
# crete int array
a = np.arange(1,6)
print((a, a.dtype))
# convert to float
af = a.astype('float64')
print((af, af.dtype))

# convert to string
a_s = a.astype('str')
print((a_s, a_s.dtype))
# convert to object
a_o = a.astype('object')
print((a_o, a_o.dtype))

(array([1, 2, 3, 4, 5]), dtype('int32'))
(array([1., 2., 3., 4., 5.]), dtype('float64'))
(array(['1', '2', '3', '4', '5'], dtype='<U11'), dtype('<U11'))
(array([1, 2, 3, 4, 5], dtype=object), dtype('O'))


#### Conversion from/to list

In [72]:
# Create list
l = [3, 4, 5, 6]
print((l, type(l)))
# list to np array
a = np.array(l)
print((a, type(a)))
# np array to list
l1 = a.tolist()
print((l, type(l1)))





([3, 4, 5, 6], <class 'list'>)
(array([3, 4, 5, 6]), <class 'numpy.ndarray'>)
([3, 4, 5, 6], <class 'list'>)


#### Statistical methods

In [70]:
# min, max, mean, std
print(a)
print(a.min())
print(a.max())
print(a.mean())
print(a.std())


[1 2 3 4 5]
1
5
3.0
1.4142135623730951
